In [121]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re

In [122]:
ruta_csv = "../src/data/HU-1.csv"
df = pd.read_csv(ruta_csv)
df["url_html_ficha_tecnica"].head()

0    https://cima.aemps.es/cima/dochtml/ft/78686/FT...
1    https://cima.aemps.es/cima/dochtml/ft/77646/FT...
2    https://cima.aemps.es/cima/dochtml/ft/78394/FT...
3    https://cima.aemps.es/cima/dochtml/ft/69576/FT...
4    https://cima.aemps.es/cima/dochtml/ft/77615/FT...
Name: url_html_ficha_tecnica, dtype: object

In [123]:
url_prueba = "https://cima.aemps.es/cima/dochtml/ft/78686/FT"

In [142]:
response = requests.get(url_prueba).text
print(response)

<!doctype html>











<html lang="es">













<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-site-verification" content="OsHcoYBxQdTF3GKC3KzwnZZ-tqCsuEkC_FcZuzElreU" />
    <meta name="description" content="FICHA TECNICA ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIERTOS CON PELICULA EFG">
    <meta name="author" content="Agencia Española de Medicamentos y Productos Sanitarios">

    <link rel="alternate" href="/cima/pdfs/es/ft/78686/FT.pdf" type="application/pdf" title="Versi&oacute;n en PDF">

    <meta http-equiv="pragma" content="no-cache">

    <title>.:: CIMA ::. FICHA TECNICA ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIERTOS CON PELICULA EFG</title>

	<link id="favicon" rel="shortcut icon" href="/cima/resources/images/favicon.ico">
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' integrity='sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u' crossorigin='anonymous'>

    <link rel='stylesheet' href='/cima/static/v1/css/bootstrap-toc.min.css' media='screen'>

    <link rel='stylesheet' href='/cima/static/v1/css/screen.css?v=3.3.3' media='screen'>
    <link rel='stylesheet' href='/cima/static/v1/css/print.css' media='print'>

</head>


<body  data-spy='scroll' data-target='#toc' data-offset="0">

	<noscript><iframe src='https://www.googletagmanager.com/ns.html?id=GTM-PDG3588' height='0' width='0' style='display:none;visibility:hidden'></iframe></noscript>

	<!-- INI BLOQUE INICIAL -->



		<!-- CON MENÚ -->
	<div class='container-fluid' id='header'>
	<nav class='navbar navbar-default navbar-fixed-top' id='fixheader'>
	   <div class='container-fluid'>
	      <div class='navbar-header'>
	        <div class="col-md-3 col-sm-12" >
	           <a class="navbar-brand" href="#">
	              <img alt="aemps" class="img-responsive2" src="https://www.aemps.gob.es/diseno/img/logo_aemps-sin-margen.jpg" style='cursor:pointer;display:inline;'>
	              <img alt="cima" class="img-responsive3" src="/cima/resources/images/CimaTranspaPeq.gif" onclick="location.href='/cima/publico/home.html'" style='cursor:pointer;display:inline'>
	           </a>
	        </div>
	        <div class="col-md-9 col-sm-12" >
	          <p class="navbar-text">FICHA TECNICA ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIERTOS CON PELICULA EFG</p>
	        </div>
	      </div>
	   </div>
	</nav>
	</div>
	<div class='container-fluid' id='content'>
		<div class='row'>
			<div class='col-md-3 col-sm-12'>
				<nav id='toc' data-spy='affix' data-toggle='toc'></nav>
			</div>
			<div class='col-md-9 col-sm-12 pvh100'>
				<div id='pdfurl' class='hidden-xs'>
					<p><strong>Pulse <a href="/cima/pdfs/es/ft/78686/FT.pdf" target='_blank' rel='noopener'>aqu&iacute;</a>

						para ver el documento en formato PDF.</strong>&nbsp;
						<a href="/cima/pdfs/es/ft/78686/FT.pdf" target='_blank'><img src='/cima/static/v1/images/Document-pdf.png' alt='icono pdf' style='width:30px;'/></a>
					</p>
				</div>



	<!-- FIN BLOQUE INICIAL -->

	<!-- INI BLOQUE PARA PINTAR EL TEXTO -->







			<h1 id="1">1. NOMBRE DEL MEDICAMENTO</h1>





		<section>


		<div>
    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">A</span><span style="font-family:Times New Roman; font-size:11pt">lmotriptán cinfa 12,5 mg comprimidos recubiertos con película EFG</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>
  </div>




		</section>




			<h1 id="2">2. COMPOSICIÓN CUALITATIVA Y CUANTITATIVA</h1>





		<section>


		<div>
    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">Cada comprimido</span> <span style="font-family:Times New Roman; font-size:11pt">recubierto</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">con</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">película</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">contiene 12,5 mg</span> <span style="font-family:Times New Roman; font-size:11pt">de</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">almotriptán</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">como</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">almotriptán</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">malato</span><span style="font-family:Times New Roman; font-size:11pt">.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">Para consultar la lista completa de excipientes, ver sección 6.1.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>
  </div>




		</section>




			<h1 id="3">3. FORMA FARMACÉUTICA</h1>





		<section>


		<div>
    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">Comprimido recubierto con pel&#237;cula (comprimido).</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">Comprimidos recubiertos con pel&#237;cula blancos, circulares y biconvexos.</span></p>

    <p style="margin:0pt; line-height:115%; font-size:11pt"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>
  </div>




		</section>




			<h1 id="4">4. DATOS CLÍNICOS</h1>





		<section>


		<div>
    <p style="margin:0pt; line-height:115%; font-size:11pt"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>
  </div>







			<h2 id="4.1">4.1. Indicaciones terapéuticas</h2>





		<div>
    <p style="margin:0pt; line-height:115%; font-size:11pt"><span style="font-family:Times New Roman; font-size:11pt">Tratamiento agudo de la fase de cefalea de las crisis de migraña con o sin aura.</span></p>
  </div>







			<h2 id="4.2">4.2. Posología y forma de administración</h2>





		<div>
    <p style="margin:0pt; text-align:justify"><strong><u><span style="font-family:Times New Roman; font-size:11pt;">Posolog&#237;a</span></u></strong></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><em><u><span style="font-family:Times New Roman; font-size:11pt;">Adultos (18-65 a&#241;os</span></u></em><em><span style="font-family:Times New Roman; font-size:11pt;">)</span></em></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">La dosis recomendada es de 12,5 mg de almotript&#225;n. Se puede tomar una segunda dosis si los s&#237;ntomas reaparecen en el plazo de 24 horas. Esta segunda dosis puede administrarse siempre que exista un intervalo m&#237;nimo de dos horas entre ambas tomas.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">No se ha estudiado en ensayos controlados la eficacia de una segunda dosis en el tratamiento del mismo ataque cuando la dosis inicial no es efectiva. Por lo tanto, si el paciente no responde a la primera dosis, no debe administrarse una segunda dosis para la misma crisis.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">La dosis m&#225;xima recomendada es de dos dosis en 24 horas.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><em><span style="font-family:Times New Roman; font-size:11pt;">Poblaci&#243;n</span></em><em><span style="font-family:Times New Roman; font-size:11pt;">&#xa0;</span></em><em><span style="font-family:Times New Roman; font-size:11pt;">pedi&#225;trica</span></em><em><span style="font-family:Times New Roman; font-size:11pt;">&#xa0;</span></em> <em><span style="font-family:Times New Roman; font-size:11pt;">&#xa0;</span></em><em><span style="font-family:Times New Roman; font-size:11pt;">(menores de 18 a&#241;os)</span></em></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">No se dispone de datos relativos al uso de almotript&#225;n en ni&#241;os y adolescentes. Por lo tanto, no se recomienda su uso en este grupo de edad.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><em><span style="font-family:Times New Roman; font-size:11pt;">Pacientes de edad avanzada (mayores de 65 a&#241;os)</span></em></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">No se necesita ajustar la dosis en pacientes de edad avanzada. La seguridad y eficacia de almotript&#225;n en pacientes mayores de 65 a&#241;os no se ha evaluado sistem&#225;ticamente.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><em><span style="font-family:Times New Roman; font-size:11pt;">Insuficiencia renal</span></em></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">No se requiere ning&#250;n ajuste de la dosis en pacientes con insuficiencia renal leve o moderada. Los pacientes con insuficiencia renal grave no deben tomar m&#225;s de un comprimido de 12,5 mg en un per&#237;odo de 24 horas.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><em><span style="font-family:Times New Roman; font-size:11pt;">Insuficiencia hep&#225;tica</span></em></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">No se ha establecido el uso de almotript&#225;n en pacientes con insuficiencia hep&#225;tica (v</span><span style="font-family:Times New Roman; font-size:11pt">er</span> <span style="font-family:Times New Roman; font-size:11pt">secciones 4.3 y 4.4).</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><strong><span style="font-family:Times New Roman; font-size:11pt;">Forma de</span></strong> <strong><span style="font-family:Times New Roman; font-size:11pt;">&#xa0;</span></strong><strong><span style="font-family:Times New Roman; font-size:11pt;">administraci&#243;n</span></strong></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">Almotript&#225;n debe tomarse, acompa&#241;ado de l&#237;quidos, tan pronto como sea posible despu&#233;s del inicio de la cefalea de origen migra&#241;oso, pero tambi&#233;n es efectivo si se toma m&#225;s tarde.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">A</span><span style="font-family:Times New Roman; font-size:11pt">lmotript&#225;n no debe</span> <span style="font-family:Times New Roman; font-size:11pt">emplearse en</span> <span style="font-family:Times New Roman; font-size:11pt">la profilaxis de la migra&#241;a.</span></p>

    <p style="margin:0pt; line-height:115%; font-size:11pt"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; line-height:115%; font-size:11pt"><span style="font-family:Times New Roman; font-size:11pt">Los</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">comprimidos</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span> <span style="font-family:Times New Roman; font-size:11pt">se</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">pueden</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">tomar</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">con</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">o</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">sin</span><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span><span style="font-family:Times New Roman; font-size:11pt">alimentos.</span></p>
  </div>







			<h2 id="4.3">4.3. Contraindicaciones</h2>





		<div>
    <ul type="disc" style="margin:0pt; padding-left:0pt">
      <li style="margin:0pt 0pt 0pt 11.04pt; text-indent:0pt; widows:0; orphans:0; padding-left:10.26pt; font-family:serif; font-size:11pt"><span style="font-family:Times New Roman; font-size:11pt">Hipersensibilidad al principio activo o a alguno de los excipientes incluidos en la secci&#243;n 6.1.</span></li>

      <li style="margin:0pt 0pt 0pt 11.04pt; text-indent:0pt; widows:0; orphans:0; padding-left:10.26pt; font-family:serif; font-size:11pt"><span style="font-family:Times New Roman; font-size:11pt">Igual que con los dem&#225;s agonistas de los receptores 5-HT1B/1D, almotript&#225;n no se debe emplear en pacientes con historia, s&#237;ntomas o signos de enfermedad isqu&#233;mica cardiaca (infarto de miocardio, angina de pecho, isquemia silente documentada, angina de Prinzmetal) o hipertensi&#243;n grave e hipertensi&#243;n leve o moderada no controlada.</span></li>

      <li style="margin:0pt 0pt 0pt 11.04pt; text-indent:0pt; widows:0; orphans:0; padding-left:10.26pt; font-family:serif; font-size:11pt"><span style="font-family:Times New Roman; font-size:11pt">Pacientes que hayan sufrido un accidente cerebrovascular o ataque isqu&#233;mico transitorio. Enfermedad vascular perif&#233;rica.</span></li>

      <li style="margin:0pt 0pt 0pt 11.04pt; text-indent:0pt; widows:0; orphans:0; padding-left:10.26pt; font-family:serif; font-size:11pt"><span style="font-family:Times New Roman; font-size:11pt">Est&#225; contraindicada la administraci&#243;n concomitante con ergotamina, derivados de la ergotamina (incluyendo metisergida) y otros agonistas 5-HT1B/1D.</span></li>
    </ul>

    <p style="margin:0pt; line-height:115%; font-size:11pt"><span style="font-family:Times New Roman; font-size:11pt">Pacientes con insuficiencia hep&#225;tica grave (v</span><span style="font-family:Times New Roman; font-size:11pt">er</span> <span style="font-family:Times New Roman; font-size:11pt">secci&#243;n 4.2).</span></p>
  </div>







			<h2 id="4.4">4.4. Advertencias y precauciones especiales de empleo</h2>





		<div>
    <p style="margin:0pt; text-align:justify"><a name="_Hlk72753734"><span style="font-family:Times New Roman; font-size:11pt">A</span><span style="font-family:Times New Roman; font-size:11pt">lmotript&#225;n s&#243;lo debe</span> <span style="font-family:Times New Roman; font-size:11pt">emplearse en casos de</span> <span style="font-family:Times New Roman; font-size:11pt">diagn&#243;stico claro de migra&#241;a, evitando su administraci&#243;n en</span> <span style="font-family:Times New Roman; font-size:11pt">la</span> <span style="font-family:Times New Roman; font-size:11pt">migra&#241;a basilar, hemipl&#233;jica u oftalmopl&#233;jica.</span></a></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">Al igual que en otros tratamientos agudos de migra&#241;a, antes de tratar la cefalea en pacientes a los que previamente no se les haya diagnosticado migra&#241;a, y en migra&#241;osos con s&#237;ntomas at&#237;picos, se debe tener la precauci&#243;n de excluir otros trastornos neurol&#243;gicos potencialmente graves. En pacientes tratados con agonistas 5HT1B/1D se han notificado accidentes cerebrovasculares y otros acontecimientos cerebrovasculares. Se debe tener en cuenta que los migra&#241;osos pueden presentar un incremento en el riesgo de ciertos acontecimientos cerebrovasculares (p.ej. accidente cerebrovascular, ataque isqu&#233;mico transitorio).</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">En muy raras ocasiones, al igual que sucede con otros agonistas de los receptores 5-HT1B/1D, se han comunicado vasoespasmo coronario e infarto de miocardio. Por lo tanto almotript&#225;n no se debe administrar en pacientes que puedan tener una enfermedad coronaria no diagnosticada sin evaluar antes la posible enfermedad cardiovascular subyacente. Entre esta poblaci&#243;n se encuentran las mujeres posmenop&#225;usicas, hombres de m&#225;s de 40 a&#241;os, y pacientes con otros factores de riesgo de padecer enfermedad coronaria como hipertensi&#243;n no controlada, hipercolesterolemia, obesidad, diabetes, tabaquismo o antecedentes evidentes de historia familiar de enfermedad cardiovascular. Sin embargo, puede que estas evaluaciones no identifiquen a todos los pacientes que padecen enfermedad cardiaca y, en muy raras ocasiones, se han producido acontecimientos cardiacos graves en pacientes sin enfermedad cardiaca subyacente tras administrarles agonistas 5-HT1.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">Tras su administraci&#243;n, almotript&#225;n puede asociarse con s&#237;ntomas transitorios, incluyendo dolor y opresi&#243;n tor&#225;cicos, que pueden ser intensos y afectar a la garganta (v</span><span style="font-family:Times New Roman; font-size:11pt">er</span> <span style="font-family:Times New Roman; font-size:11pt">secci&#243;n 4.8). Dado que estos s&#237;ntomas se relacionan con la enfermedad cardiaca isqu&#233;mica, debe interrumpirse la administraci&#243;n de nuevas dosis y efectuarse una evaluaci&#243;n adecuada.</span></p>

    <p style="margin:0pt; text-align:justify"><span style="font-family:Times New Roman; font-size:11pt">&#xa0;</span></p>


In [125]:
soup = BeautifulSoup(response, 'html.parser')

In [126]:
seccion_4_4 = soup.find('h2', id = '4.4')
seccion_4_4

In [127]:
contenido_4_4 = seccion_4_4.find_next()
#p = contenido_4_4.find_next()
#parent = p.parent()
#parent
#contenido_4_4.text
contenido_4_4.get_text(strip = True)

'Almotriptán sólo debeemplearse en casos dediagnóstico claro de migraña, evitando su administración enlamigraña basilar, hemipléjica u oftalmopléjica.Al igual que en otros tratamientos agudos de migraña, antes de tratar la cefalea en pacientes a los que previamente no se les haya diagnosticado migraña, y en migrañosos con síntomas atípicos, se debe tener la precaución de excluir otros trastornos neurológicos potencialmente graves. En pacientes tratados con agonistas 5HT1B/1D se han notificado accidentes cerebrovasculares y otros acontecimientos cerebrovasculares. Se debe tener en cuenta que los migrañosos pueden presentar un incremento en el riesgo de ciertos acontecimientos cerebrovasculares (p.ej. accidente cerebrovascular, ataque isquémico transitorio).En muy raras ocasiones, al igual que sucede con otros agonistas de los receptores 5-HT1B/1D, se han comunicado vasoespasmo coronario e infarto de miocardio. Por lo tanto almotriptán no se debe administrar en pacientes que puedan tener una enfermedad coronaria no diagnosticada sin evaluar antes la posible enfermedad cardiovascular subyacente. Entre esta población se encuentran las mujeres posmenopáusicas, hombres de más de 40 años, y pacientes con otros factores de riesgo de padecer enfermedad coronaria como hipertensión no controlada, hipercolesterolemia, obesidad, diabetes, tabaquismo o antecedentes evidentes de historia familiar de enfermedad cardiovascular. Sin embargo, puede que estas evaluaciones no identifiquen a todos los pacientes que padecen enfermedad cardiaca y, en muy raras ocasiones, se han producido acontecimientos cardiacos graves en pacientes sin enfermedad cardiaca subyacente tras administrarles agonistas 5-HT1.Tras su administración, almotriptán puede asociarse con síntomas transitorios, incluyendo dolor y opresión torácicos, que pueden ser intensos y afectar a la garganta (versección 4.8). Dado que estos síntomas se relacionan con la enfermedad cardiaca isquémica, debe interrumpirse la administración de nuevas dosis y efectuarse una evaluación adecuada.Almotriptán debe administrarse con cautela en pacientes con hipersensibilidad conocida a las sulfonamidas.Se ha comunicado la aparición de síndrome serotoninérgico (incluyendo estado mental alterado, inestabilidad autonómica y anomalías neuromusculares) tras el tratamiento concomitante con triptanes e inhibidores selectivos de la recaptación de serotonina (ISRS) o inhibidores de la recaptación de serotonina y noradrenalina (IRSN). Estas reacciones pueden ser graves. Si se justifica clínicamente el tratamiento concomitante de almotriptán y un ISRS o un IRSN, se recomienda un seguimiento adecuado del paciente, especialmente durante el inicio del tratamiento, con los incrementos de dosis o con la adición de otra medicación serotoninérgica (ver sección 4.5).Tras utilizar almotriptán se recomienda esperar como mínimo 6 horas antes de administrar ergotamina. Tras la administración de un preparado que contenga ergotamina, deben transcurrir por lo menos 24 horas antes de administrar almotriptán. A pesar de que no se observaron efectos vasoespásticos aditivos en un ensayo clínico en el que se administraron almotriptán y ergotamina por vía oral a 12 sujetos sanos, dichos efectos aditivos son teóricamente posibles (versección 4.3).Los pacientes con insuficiencia renal grave no deben tomar más de un comprimido de 12,5 mg en un período de 24 horas.Se recomienda precaución en pacientes con enfermedad hepática leve o moderada. El tratamiento está contraindicado en pacientes con enfermedad hepática grave (versección 5.2).Las reacciones adversas pueden ser más habituales durante el uso concomitante de triptanes y preparados a base de Hierba de San Juan (Hypericum perforatum).Al igual que otros agonistas de los receptores 5-HT1B/1D, almotriptán puede provocar un aumento transitorio y moderado de la presión sanguínea, que puede ser más pronunciado en las personas de edad avanzada.Cefalea por uso excesivo de medicamentos(MOH)La cefalea puede empeorar con el uso prolongado de cualquier analgésico para su tratamiento. Si se experimenta o sospecha esta situación, debe requerirse consejo médico e interrumpirse el tratamiento. El diagnóstico de la cefalea por uso excesivo de medicamentos debe sospecharse en pacientes que sufren cefaleas diarias o frecuentes a pesar del uso habitual de medicamentos para las mismas.No se debe superar la dosis máxima recomendada de almotriptán.Advertencia sobre excipientesEste medicamento contiene menos de 23 mg de sodio (1 mmol) por comprimido; esto es, esencialmente “exento de sodio”.'

In [128]:
cont = soup.get_text(" ",strip=True).lower()
palabras = re.findall(r"\bgraves?\b", cont)
palabras

['grave',
 'grave',
 'grave',
 'graves',
 'graves',
 'graves',
 'grave',
 'grave',
 'grave',
 'grave',
 'grave',
 'grave',
 'grave',
 'grave']

In [129]:
num_palabras_4_4 = len(contenido_4_4.text.split())
num_palabras_4_4

659

In [130]:
tablas = soup.find_all('table')
len(tablas)

1

In [131]:
texto = soup.text
texto = texto.lower()
lista_graves = re.findall(r'\bgraves?\b', texto)
len_graves = len(lista_graves)
lista_graves

['grave',
 'grave',
 'grave',
 'graves',
 'graves',
 'graves',
 'grave',
 'grave',
 'grave',
 'grave',
 'grave',
 'grave',
 'grave',
 'grave']

In [132]:
len(lista_graves) == len(palabras)

True

In [133]:
df.head()

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,generico,afecta_conduccion,triangulo_negro,medicamento_huerfano,biosimilar,url_html_ficha_tecnica,url_foto_materiales,num_registros_atc,num_principios_activos,num_excipientes
0,78686,"ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,702112,"12,5 mg",COMPRIMIDO,1397652220000,NaN,...,True,1,0,0,False,https://cima.aemps.es/cima/dochtml/ft/78686/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN
1,77646,"ALMOTRIPTAN NORMON 12,5 MG COMPRIMIDOS RECUBIE...",ALMOTRIPTAN,Laboratorios Normon S.A.,Laboratorios Normon S.A.,698376,"12,5 mg",COMPRIMIDO,1371536710000,NaN,...,True,1,0,0,False,https://cima.aemps.es/cima/dochtml/ft/77646/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN
2,78394,"ALMOTRIPTAN STADA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorio Stada S.L.,Laboratorio Stada S.L.,701248,"12,5 MG",COMPRIMIDO,1390777200000,NaN,...,True,1,0,0,False,https://cima.aemps.es/cima/dochtml/ft/78394/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN
3,69576,IBUPROFENO (ARGININA) KERN PHARMA 600 mg GRANU...,IBUPROFENO,Kern Pharma S.L.,Kern Pharma S.L.,660476,600 mg,SOLUCIÓN/SUSPENSIÓN ORAL,1201647600000,NaN,...,True,0,0,0,False,https://cima.aemps.es/cima/dochtml/ft/69576/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN
4,77615,IBUPROFENO STADA 600 MG COMPRIMIDOS RECUBIERTO...,IBUPROFENO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,698275,600 mg,COMPRIMIDO,1370901600000,NaN,...,True,0,0,0,False,https://cima.aemps.es/cima/dochtml/ft/77615/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN

In [134]:
df["Volumen_Informativo"] = num_palabras_4_4
df["Complejidad"] = len(tablas)
df["Indicador_Riesgo"] = len_graves

In [135]:
df.head()

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,medicamento_huerfano,biosimilar,url_html_ficha_tecnica,url_foto_materiales,num_registros_atc,num_principios_activos,num_excipientes,Volumen_Informativo,Complejidad,Indicador_Riesgo
0,78686,"ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,702112,"12,5 mg",COMPRIMIDO,1397652220000,NaN,...,0,False,https://cima.aemps.es/cima/dochtml/ft/78686/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN,659,1,14
1,77646,"ALMOTRIPTAN NORMON 12,5 MG COMPRIMIDOS RECUBIE...",ALMOTRIPTAN,Laboratorios Normon S.A.,Laboratorios Normon S.A.,698376,"12,5 mg",COMPRIMIDO,1371536710000,NaN,...,0,False,https://cima.aemps.es/cima/dochtml/ft/77646/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN,659,1,14
2,78394,"ALMOTRIPTAN STADA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorio Stada S.L.,Laboratorio Stada S.L.,701248,"12,5 MG",COMPRIMIDO,1390777200000,NaN,...,0,False,https://cima.aemps.es/cima/dochtml/ft/78394/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN,659,1,14
3,69576,IBUPROFENO (ARGININA) KERN PHARMA 600 mg GRANU...,IBUPROFENO,Kern Pharma S.L.,Kern Pharma S.L.,660476,600 mg,SOLUCIÓN/SUSPENSIÓN ORAL,1201647600000,NaN,...,0,False,https://cima.aemps.es/cima/dochtml/ft/69576/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN,659,1,14
4,77615,IBUPROFENO STADA 600 MG COMPRIMIDOS RECUBIERTO...,IBUPROFENO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,698275,600 mg,COMPRIMIDO,1370901600000,NaN,...,0,False,https://cima.aemps.es/cima/dochtml/ft/77615/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN,659,1,14

In [136]:
ruta_csv = "../src/data/HU-1.csv"
df = pd.read_csv(ruta_csv)
df["url_html_ficha_tecnica"].head()

0    https://cima.aemps.es/cima/dochtml/ft/78686/FT...
1    https://cima.aemps.es/cima/dochtml/ft/77646/FT...
2    https://cima.aemps.es/cima/dochtml/ft/78394/FT...
3    https://cima.aemps.es/cima/dochtml/ft/69576/FT...
4    https://cima.aemps.es/cima/dochtml/ft/77615/FT...
Name: url_html_ficha_tecnica, dtype: object

In [144]:
volumenes = []
complejidades = []
indicadores = []

for index, row in df.iterrows():
    link = row["url_html_ficha_tecnica"]
    response = requests.get(link).text
    #print(response)
    soup = BeautifulSoup(response, 'html.parser')

    seccion_4_4 = soup.find(id='4.4')
    contenido_4_4 = seccion_4_4.find_next()
    palabras_4_4 = contenido_4_4.get_text(strip = True).split()
    num_palabras = len(palabras_4_4)
    volumenes.append(num_palabras)

    tablas = soup.find_all('table')
    num_tablas = len(tablas)
    complejidades.append(num_tablas)

    texto_medicamento = soup.get_text(" ", strip=True).lower()
    lista_graves = re.findall(r'\bgraves?\b', texto_medicamento)
    num_graves = len(lista_graves)
    indicadores.append(num_graves)

df["Volumen_Informativo"] = volumenes
df["Complejidad"] = complejidades
df["Indicador_Riesgo"] = indicadores

#df.head()

In [145]:
df.head()

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,medicamento_huerfano,biosimilar,url_html_ficha_tecnica,url_foto_materiales,num_registros_atc,num_principios_activos,num_excipientes,Volumen_Informativo,Complejidad,Indicador_Riesgo
0,78686,"ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,702112,"12,5 mg",COMPRIMIDO,1397652220000,NaN,...,0,False,https://cima.aemps.es/cima/dochtml/ft/78686/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN,636,1,14
1,77646,"ALMOTRIPTAN NORMON 12,5 MG COMPRIMIDOS RECUBIE...",ALMOTRIPTAN,Laboratorios Normon S.A.,Laboratorios Normon S.A.,698376,"12,5 mg",COMPRIMIDO,1371536710000,NaN,...,0,False,https://cima.aemps.es/cima/dochtml/ft/77646/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN,662,1,13
2,78394,"ALMOTRIPTAN STADA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorio Stada S.L.,Laboratorio Stada S.L.,701248,"12,5 MG",COMPRIMIDO,1390777200000,NaN,...,0,False,https://cima.aemps.es/cima/dochtml/ft/78394/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN,650,1,13
3,69576,IBUPROFENO (ARGININA) KERN PHARMA 600 mg GRANU...,IBUPROFENO,Kern Pharma S.L.,Kern Pharma S.L.,660476,600 mg,SOLUCIÓN/SUSPENSIÓN ORAL,1201647600000,NaN,...,0,False,https://cima.aemps.es/cima/dochtml/ft/69576/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN,1375,0,12
4,77615,IBUPROFENO STADA 600 MG COMPRIMIDOS RECUBIERTO...,IBUPROFENO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,698275,600 mg,COMPRIMIDO,1370901600000,NaN,...,0,False,https://cima.aemps.es/cima/dochtml/ft/77615/FT...,https://cima.aemps.es/cima/fotos/thumbnails/ma...,3,1,NaN,1238,0,13

In [146]:
df.to_csv("../src/data/HU-2.csv", index=False)