In [2]:
import pandas as pd

In [3]:
ruta = "../src/data/HU-2.csv"
df_migraña = pd.read_csv(ruta)

In [4]:
ruta = "../src/data/Nomenclator.csv"
df_total = pd.read_csv(ruta)

In [5]:
df_final = pd.merge(df_migraña, df_total[["Código Nacional","Estado","Precio venta al público con IVA","Precio de referencia", \
        "Tratamiento de larga duración", "Especial control médico"]], left_on = 'cn', right_on='Código Nacional', how="left")
df_final.head()

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,num_excipientes,Volumen_Informativo,Complejidad,Indicador_Riesgo,Código Nacional,Estado,Precio venta al público con IVA,Precio de referencia,Tratamiento de larga duración,Especial control médico
0,78686,"ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,702112,"12,5 mg",COMPRIMIDO,1397652220000,NaN,...,NaN,636,1,14,NaN,NaN,NaN,NaN,NaN,NaN
1,77646,"ALMOTRIPTAN NORMON 12,5 MG COMPRIMIDOS RECUBIE...",ALMOTRIPTAN,Laboratorios Normon S.A.,Laboratorios Normon S.A.,698376,"12,5 mg",COMPRIMIDO,1371536710000,NaN,...,NaN,662,1,13,698376.0,ALTA,19.53,19.53,NO,NO
2,78394,"ALMOTRIPTAN STADA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorio Stada S.L.,Laboratorio Stada S.L.,701248,"12,5 MG",COMPRIMIDO,1390777200000,NaN,...,NaN,650,1,13,701248.0,ALTA,19.53,19.53,NO,NO
3,69576,IBUPROFENO (ARGININA) KERN PHARMA 600 mg GRANU...,IBUPROFENO,Kern Pharma S.L.,Kern Pharma S.L.,660476,600 mg,SOLUCIÓN/SUSPENSIÓN ORAL,1201647600000,NaN,...,NaN,1375,0,12,660476.0,BAJA POR NO COMERCIALIZAR,2.50,2.50,NO,NO
4,77615,IBUPROFENO STADA 600 MG COMPRIMIDOS RECUBIERTO...,IBUPROFENO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,698275,600 mg,COMPRIMIDO,1370901600000,NaN,...,NaN,1238,0,13,698275.0,ALTA,1.97,1.97,NO,NO

In [6]:
df_final = pd.merge(left=df_migraña, right=df_total[["Código Nacional","Estado","Precio venta al público con IVA","Precio de referencia", \
        "Tratamiento de larga duración", "Especial control médico"]], left_on='cn', right_on='Código Nacional', how='left')
df_final.head()

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,num_excipientes,Volumen_Informativo,Complejidad,Indicador_Riesgo,Código Nacional,Estado,Precio venta al público con IVA,Precio de referencia,Tratamiento de larga duración,Especial control médico
0,78686,"ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,702112,"12,5 mg",COMPRIMIDO,1397652220000,NaN,...,NaN,636,1,14,NaN,NaN,NaN,NaN,NaN,NaN
1,77646,"ALMOTRIPTAN NORMON 12,5 MG COMPRIMIDOS RECUBIE...",ALMOTRIPTAN,Laboratorios Normon S.A.,Laboratorios Normon S.A.,698376,"12,5 mg",COMPRIMIDO,1371536710000,NaN,...,NaN,662,1,13,698376.0,ALTA,19.53,19.53,NO,NO
2,78394,"ALMOTRIPTAN STADA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorio Stada S.L.,Laboratorio Stada S.L.,701248,"12,5 MG",COMPRIMIDO,1390777200000,NaN,...,NaN,650,1,13,701248.0,ALTA,19.53,19.53,NO,NO
3,69576,IBUPROFENO (ARGININA) KERN PHARMA 600 mg GRANU...,IBUPROFENO,Kern Pharma S.L.,Kern Pharma S.L.,660476,600 mg,SOLUCIÓN/SUSPENSIÓN ORAL,1201647600000,NaN,...,NaN,1375,0,12,660476.0,BAJA POR NO COMERCIALIZAR,2.50,2.50,NO,NO
4,77615,IBUPROFENO STADA 600 MG COMPRIMIDOS RECUBIERTO...,IBUPROFENO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,698275,600 mg,COMPRIMIDO,1370901600000,NaN,...,NaN,1238,0,13,698275.0,ALTA,1.97,1.97,NO,NO

In [7]:
ruta_output = "../src/data/HU-3.csv"
df_final.to_csv(ruta_output, index=False)