# HU-4

Notebook para trabajar en la Historia de Usuario 4

In [99]:
import pandas as pd
from pathlib import Path

In [100]:
ruta = Path("../src/data/catalogo_enriquecido.xlsx")
df = pd.read_excel(ruta, index_col = False)

In [101]:
df.head()

,Unnamed: 0,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,num_excipientes,Volumen_Informativo,Complejidad_Desglose,Indicador_Riesgo,Código Nacional,Estado,Precio venta al público con IVA,Precio de referencia,Tratamiento de larga duración,Especial control médico
0,0,78686,"ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,702112,COMPRIMIDO,1970-01-01 01:00:41.745,NaT,...,0,659,1,5,NaN,NaN,NaN,NaN,NaN,NaN
1,1,77646,"ALMOTRIPTAN NORMON 12,5 MG COMPRIMIDOS RECUBIE...",ALMOTRIPTAN,Laboratorios Normon S.A.,Laboratorios Normon S.A.,698376,COMPRIMIDO,1970-01-01 01:00:41.443,NaT,...,0,678,1,5,698376.0,ALTA,19.53,19.53,NO,NO
2,2,78394,"ALMOTRIPTAN STADA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorio Stada S.L.,Laboratorio Stada S.L.,701248,COMPRIMIDO,1970-01-01 01:00:41.665,NaT,...,0,666,1,5,701248.0,ALTA,19.53,19.53,NO,NO
3,3,69576,IBUPROFENO (ARGININA) KERN PHARMA 600 mg GRANU...,IBUPROFENO,Kern Pharma S.L.,Kern Pharma S.L.,660476,SOLUCIÓN/SUSPENSIÓN ORAL,1970-01-01 01:00:39.476,NaT,...,0,1432,0,4,660476.0,BAJA POR NO COMERCIALIZAR,2.50,2.50,NO,NO
4,4,77615,IBUPROFENO STADA 600 MG COMPRIMIDOS RECUBIERTO...,IBUPROFENO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,698275,COMPRIMIDO,1970-01-01 01:00:41.435,NaT,...,0,1279,0,4,698275.0,ALTA,1.97,1.97,NO,NO

## Eliminamos columnas inútiles

In [102]:
df.columns

Index(['Unnamed: 0', 'nregistro', 'nombre', 'pactivos', 'labtitular',
       'labcomercializador', 'cn', 'forma_farmaceutica_simplificada',
       'estado_aut', 'estado_rev', 'vias_administracion', 'comercializado',
       'requiere_receta', 'generico', 'afecta_conduccion', 'triangulo_negro',
       'medicamento_huerfano', 'biosimilar', 'url_html_ficha_tecnica',
       'url_foto_materiales', 'num_registros_atc', 'num_principios_activos',
       'num_excipientes', 'Volumen_Informativo', 'Complejidad_Desglose',
       'Indicador_Riesgo', 'Código Nacional', 'Estado',
       'Precio venta al público con IVA', 'Precio de referencia',
       'Tratamiento de larga duración', 'Especial control médico'],
      dtype='object')

In [103]:
columnas_a_eliminar = [
    "cn",
    "Código Nacional", #Ya aparecen en "cn", además tiene muchos nulos
    "url_html_ficha_tecnica",
    "url_foto_materiales"
]
# además, la primera columna, que es un index

In [104]:
df.drop(columnas_a_eliminar, axis = 1, inplace = True)
df.drop(df.columns[0], axis = 1, inplace = True)

## Gestionamos filas duplicadas

Primero revisamos si hay medicamentos con el nombre duplicado:
- Si los hay, eliminamos los duplicados por `nregistro`. (Podría haber medicamentos con el mismo nombre pero distinto nregistro, quizás con distintos componentes)
- Si no los hay, eliminamos la columna `nregistro`.

In [105]:
nombres_duplicados = int(df["nombre"].duplicated().sum())
print(f"Hay {nombres_duplicados} medicamentos duplicados")

Hay 0 medicamentos duplicados

In [106]:
df.drop("nregistro", axis = 1, inplace = True)

In [108]:
df.head()

,nombre,pactivos,labtitular,labcomercializador,forma_farmaceutica_simplificada,estado_aut,estado_rev,vias_administracion,comercializado,requiere_receta,...,num_principios_activos,num_excipientes,Volumen_Informativo,Complejidad_Desglose,Indicador_Riesgo,Estado,Precio venta al público con IVA,Precio de referencia,Tratamiento de larga duración,Especial control médico
0,"ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,COMPRIMIDO,1970-01-01 01:00:41.745,NaT,VÍA ORAL,1,1,...,1,0,659,1,5,NaN,NaN,NaN,NaN,NaN
1,"ALMOTRIPTAN NORMON 12,5 MG COMPRIMIDOS RECUBIE...",ALMOTRIPTAN,Laboratorios Normon S.A.,Laboratorios Normon S.A.,COMPRIMIDO,1970-01-01 01:00:41.443,NaT,VÍA ORAL,1,1,...,1,0,678,1,5,ALTA,19.53,19.53,NO,NO
2,"ALMOTRIPTAN STADA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorio Stada S.L.,Laboratorio Stada S.L.,COMPRIMIDO,1970-01-01 01:00:41.665,NaT,VÍA ORAL,1,1,...,1,0,666,1,5,ALTA,19.53,19.53,NO,NO
3,IBUPROFENO (ARGININA) KERN PHARMA 600 mg GRANU...,IBUPROFENO,Kern Pharma S.L.,Kern Pharma S.L.,SOLUCIÓN/SUSPENSIÓN ORAL,1970-01-01 01:00:39.476,NaT,VÍA ORAL,1,1,...,1,0,1432,0,4,BAJA POR NO COMERCIALIZAR,2.50,2.50,NO,NO
4,IBUPROFENO STADA 600 MG COMPRIMIDOS RECUBIERTO...,IBUPROFENO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,COMPRIMIDO,1970-01-01 01:00:41.435,NaT,VÍA ORAL,1,1,...,1,0,1279,0,4,ALTA,1.97,1.97,NO,NO

## Gestionamos valores nulos

Queremos mirar qué columnas tienen valores nulos.

In [ ]:
df.isna().sum()

nregistro                           0
nombre                              0
pactivos                            0
labtitular                          0
labcomercializador                  0
cn                                  0
forma_farmaceutica_simplificada     0
estado_aut                          0
estado_rev                         51
vias_administracion                 0
comercializado                      0
requiere_receta                     0
generico                            0
afecta_conduccion                   0
triangulo_negro                     0
medicamento_huerfano                0
biosimilar                          0
num_registros_atc                   0
num_principios_activos              0
num_excipientes                     0
Volumen_Informativo                 0
Complejidad_Desglose                0
Indicador_Riesgo                    0
Estado                             22
Precio venta al público con IVA    22
Precio de referencia               23
Tratamiento de larga duración      22
Especial control médico            22
dtype: int64

## Comentarios de Guillermo y Emilio
- Al ser nuestro dataset muy pequeño (70 filas), el EDA es muy importante

- Cualquier cambio en él, influye más que en un dataset de 10_000 filas.

- La decisión de qué hacer con los valores nulos es nuestra. Aquí tenemos 22 de 70 (~31%)

- Poner la media es una mala decisión. El objetivo de HU-5 es clusterizar, y si asignamos la media a todos esos nulos, 
sesgamos el modelo hacia un único cluster (que estaría centrado más o menos en la media)

- Esto provocaría casos como: incluir un ibuprofeno en un cluster cuyo precio es 100€ (no tiene sentido)

- Guillermo sugirió dar valores aleatorios en un rango.

- ¡Ojo! A veces pensamos que los nulos se deben a "falta de información", pero se puede deducir por qué en otras columnas de la tabla. Por ejemplo, los nulos de `precio_de_venta` se deben a que no están comercializados.

- También podría haber algunos nulos (como fechas) que quizás no sean tan importantes

In [110]:
df.describe()

,estado_aut,estado_rev,comercializado,requiere_receta,generico,afecta_conduccion,triangulo_negro,medicamento_huerfano,biosimilar,num_registros_atc,num_principios_activos,num_excipientes,Volumen_Informativo,Complejidad_Desglose,Indicador_Riesgo,Precio venta al público con IVA,Precio de referencia
count,70,19,70.000000,70.0,70.000000,70.000000,70.0,70.0,70.0,70.0,70.000000,70.0,70.000000,70.000000,70.000000,48.000000,47.000000
mean,1970-01-01 01:00:38.083642857,1970-01-01 01:00:45.219842105,0.700000,1.0,0.742857,0.657143,0.0,0.0,0.0,3.0,1.014286,0.0,1159.785714,1.657143,3.614286,16.357500,16.250213
min,1970-01-01 01:00:19.875000,1970-01-01 01:00:44.515000,0.000000,1.0,0.000000,0.000000,0.0,0.0,0.0,3.0,1.000000,0.0,380.000000,0.000000,0.000000,0.170000,0.170000
25%,1970-01-01 01:00:38.694000,1970-01-01 01:00:44.852500,0.000000,1.0,0.250000,0.000000,0.0,0.0,0.0,3.0,1.000000,0.0,664.500000,0.000000,2.000000,2.060000,2.060000
50%,1970-01-01 01:00:39.252000,1970-01-01 01:00:45.208000,1.000000,1.0,1.000000,1.000000,0.0,0.0,0.0,3.0,1.000000,0.0,1262.000000,1.000000,3.000000,8.800000,8.800000
75%,1970-01-01 01:00:39.939250,1970-01-01 01:00:45.673000,1.000000,1.0,1.000000,1.000000,0.0,0.0,0.0,3.0,1.000000,0.0,1584.000000,3.000000,5.000000,19.530000,18.920000
max,1970-01-01 01:00:42.551000,1970-01-01 01:00:46.072000,1.000000,1.0,1.000000,1.000000,0.0,0.0,0.0,3.0,2.000000,0.0,1837.000000,6.000000,6.000000,73.250000,73.250000
std,NaN,NaN,0.461566,0.0,0.440215,0.478091,0.0,0.0,0.0,0.0,0.119523,0.0,483.133189,1.667122,1.535029,20.206262,20.410890

## Siguiente tarea

- Validar datos (quizás Pydantic)

- Revisar formatos fechas y ver si son importantes para el modelo