In [6]:
import os
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [3]:
print(os.getcwd())

/Users/santiago/Desktop/Data Engineering/Proyecto-Ingenieria-Dato/Notebooks

In [4]:
PATH = os.getcwd() + "/../src/data/HU4_EDA.csv"
df = pd.read_csv(PATH)

In [7]:
df.head()

,nombre,pactivos,labtitular,labcomercializador,dosis (mg),forma_farmaceutica_simplificada,estado_aut,estado_rev,vias_administracion,comercializado,generico,afecta_conduccion,num_principios_activos,Volumen_Informativo,Complejidad_Desglose,Indicador_Riesgo,Estado,Precio venta al público con IVA,Tratamiento de larga duración
0,"ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,12.5,COMPRIMIDO,2014,2014,VÍA ORAL,1,1,1,1,636,1,14,ALTA,14.704801,0
1,"ALMOTRIPTAN NORMON 12,5 MG COMPRIMIDOS RECUBIE...",ALMOTRIPTAN,Laboratorios Normon S.A.,Laboratorios Normon S.A.,12.5,COMPRIMIDO,2013,2013,VÍA ORAL,1,1,1,1,662,1,13,ALTA,19.530000,0
2,"ALMOTRIPTAN STADA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorio Stada S.L.,Laboratorio Stada S.L.,12.5,COMPRIMIDO,2014,2014,VÍA ORAL,1,1,1,1,650,1,13,ALTA,19.530000,0
3,IBUPROFENO (ARGININA) KERN PHARMA 600 mg GRANU...,IBUPROFENO,Kern Pharma S.L.,Kern Pharma S.L.,600.0,SOLUCIÓN,2008,2008,VÍA ORAL,1,1,0,1,1375,0,12,BAJA POR NO COMERCIALIZAR,2.500000,0
4,IBUPROFENO STADA 600 MG COMPRIMIDOS RECUBIERTO...,IBUPROFENO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,600.0,COMPRIMIDO,2013,2013,VÍA ORAL,1,1,0,1,1238,0,13,ALTA,1.970000,0

In [8]:
df.dtypes

nombre                                 str
pactivos                               str
labtitular                             str
labcomercializador                     str
dosis (mg)                         float64
forma_farmaceutica_simplificada        str
estado_aut                           int64
estado_rev                           int64
vias_administracion                    str
comercializado                       int64
generico                             int64
afecta_conduccion                    int64
num_principios_activos               int64
Volumen_Informativo                  int64
Complejidad_Desglose                 int64
Indicador_Riesgo                     int64
Estado                                 str
Precio venta al público con IVA    float64
Tratamiento de larga duración        int64
dtype: object

In [ ]:
df["estado_aut"] = pd.to_datetime(df["estado_aut"])
df["estado_rev"] = pd.to_datetime(df["estado_rev"])
print(df.dtypes)

nombre                                        str
pactivos                                      str
labtitular                                    str
labcomercializador                            str
dosis (mg)                                float64
forma_farmaceutica_simplificada               str
estado_aut                         datetime64[us]
estado_rev                         datetime64[us]
vias_administracion                           str
comercializado                              int64
generico                                    int64
afecta_conduccion                           int64
num_principios_activos                      int64
Volumen_Informativo                         int64
Complejidad_Desglose                        int64
Indicador_Riesgo                            int64
Estado                                        str
Precio venta al público con IVA           float64
Tratamiento de larga duración                 str
dtype: object

In [ ]:
df["aut_day"] = df["estado_aut"].dt.day
df["aut_month"] = df["estado_aut"].dt.month
df["aut_year"] = df["estado_aut"].dt.year

df["rev_day"] = df["estado_rev"].dt.day
df["rev_month"] = df["estado_rev"].dt.month
df["rev_year"] = df["estado_rev"].dt.year

df.drop(["estado_aut", "estado_rev"], axis=1, inplace=True)
df.dtypes

nombre                                 str
pactivos                               str
labtitular                             str
labcomercializador                     str
dosis (mg)                         float64
forma_farmaceutica_simplificada        str
vias_administracion                    str
comercializado                       int64
generico                             int64
afecta_conduccion                    int64
num_principios_activos               int64
Volumen_Informativo                  int64
Complejidad_Desglose                 int64
Indicador_Riesgo                     int64
Estado                                 str
Precio venta al público con IVA    float64
Tratamiento de larga duración          str
aut_day                              int32
aut_month                            int32
aut_year                             int32
rev_day                              int32
rev_month                            int32
rev_year                             int32
dtype: object

In [ ]:
names = df["nombre"].values
print(names.shape)

(70,)

In [ ]:
df.drop("nombre", inplace=True, axis=1)

In [ ]:
text_columns = df.select_dtypes(include=['str']).columns
print(text_columns)

Index(['pactivos', 'labtitular', 'labcomercializador',
       'forma_farmaceutica_simplificada', 'vias_administracion', 'Estado',
       'Tratamiento de larga duración'],
      dtype='str')

In [ ]:
encoder = preprocessing.OneHotEncoder(handle_unknown='error', min_frequency=0.7)
encoded_data = encoder.fit_transform(df[text_columns])

encoded_df = pd.DataFrame(
    encoded_data.toarray(),
    columns=encoder.get_feature_names_out(text_columns)
)

final_df = pd.concat(
    [df.drop(columns=text_columns), encoded_df],
    axis=1
)
final_df.head()

,dosis (mg),comercializado,generico,afecta_conduccion,num_principios_activos,Volumen_Informativo,Complejidad_Desglose,Indicador_Riesgo,Precio venta al público con IVA,aut_day,...,labtitular_infrequent_sklearn,labcomercializador_infrequent_sklearn,forma_farmaceutica_simplificada_COMPRIMIDO,forma_farmaceutica_simplificada_infrequent_sklearn,vias_administracion_VÍA ORAL,vias_administracion_infrequent_sklearn,Estado_ALTA,Estado_infrequent_sklearn,Tratamiento de larga duración_NO,Tratamiento de larga duración_infrequent_sklearn
0,12.5,1,1,1,1,636,1,14,32.085076,16,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,12.5,1,1,1,1,662,1,13,19.530000,18,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,12.5,1,1,1,1,650,1,13,19.530000,26,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,600.0,1,1,0,1,1375,0,12,2.500000,29,...,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
4,600.0,1,1,0,1,1238,0,13,1.970000,10,...,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [ ]:
X = df.to_numpy()
print(X.shape)

(70, 22)

# Santi

In [10]:
df = pd.read_csv(os.getcwd() + "/../src/data/HU4_EDA.csv")
df.head()

,nombre,pactivos,labtitular,labcomercializador,dosis (mg),forma_farmaceutica_simplificada,estado_aut,estado_rev,vias_administracion,comercializado,generico,afecta_conduccion,num_principios_activos,Volumen_Informativo,Complejidad_Desglose,Indicador_Riesgo,Estado,Precio venta al público con IVA,Tratamiento de larga duración
0,"ALMOTRIPTAN CINFA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,12.5,COMPRIMIDO,2014,2014,VÍA ORAL,1,1,1,1,636,1,14,ALTA,14.704801,0
1,"ALMOTRIPTAN NORMON 12,5 MG COMPRIMIDOS RECUBIE...",ALMOTRIPTAN,Laboratorios Normon S.A.,Laboratorios Normon S.A.,12.5,COMPRIMIDO,2013,2013,VÍA ORAL,1,1,1,1,662,1,13,ALTA,19.530000,0
2,"ALMOTRIPTAN STADA 12,5 MG COMPRIMIDOS RECUBIER...",ALMOTRIPTAN,Laboratorio Stada S.L.,Laboratorio Stada S.L.,12.5,COMPRIMIDO,2014,2014,VÍA ORAL,1,1,1,1,650,1,13,ALTA,19.530000,0
3,IBUPROFENO (ARGININA) KERN PHARMA 600 mg GRANU...,IBUPROFENO,Kern Pharma S.L.,Kern Pharma S.L.,600.0,SOLUCIÓN,2008,2008,VÍA ORAL,1,1,0,1,1375,0,12,BAJA POR NO COMERCIALIZAR,2.500000,0
4,IBUPROFENO STADA 600 MG COMPRIMIDOS RECUBIERTO...,IBUPROFENO,Laboratorio Stada S.L.,Laboratorio Stada S.L.,600.0,COMPRIMIDO,2013,2013,VÍA ORAL,1,1,0,1,1238,0,13,ALTA,1.970000,0

## Variables categóricas Sí/No

In [18]:
nominal_features = [
    "comercializado",
    "generico",
    "afecta_conduccion",
    "Tratamiento de larga duración"
]

In [19]:
#Comentarios con documentación de Scikit learn
nominal_encoder = OneHotEncoder(
    sparse_output=False, #When True, it returns a SciPy sparse matrix/array in “Compressed Sparse Row” (CSR) format
    handle_unknown='ignore'
)

In [20]:
X=df.drop("nombre", axis=1)

nominal_encoded = nominal_encoder.fit_transform(X[nominal_features])

nominal_encoded_df = pd.DataFrame(
    nominal_encoded,
    columns=nominal_encoder.get_feature_names_out(nominal_features),
    index=X.index,
)

nominal_encoded_df.head()

,comercializado_0,comercializado_1,generico_0,generico_1,afecta_conduccion_0,afecta_conduccion_1,Tratamiento de larga duración_0,Tratamiento de larga duración_1
0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
1,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
3,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
4,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0